### PR TITLE
[1.x] Bacon QR 3.0 support

### PR DESCRIPTION
**Pull request by eshimischi**
https://github.com/Bacon/BaconQrCode/releases/tag/v3.0.0

### CODE REVIEW

**Comment by driesvints** [comment]
Tbh, think we can just bump to 3.0 since we're also at a minimum of PHP 8.1

**Comment by eshimischi** [comment]
> Tbh, think we can just bump to 3.0 since we're also at a minimum of PHP 8.1

Yes indeed! I checked my personal project with 3.0, no issues

**Comment by Jhamnerx** [comment]
When updating to this version I have not been able to install
simplesoftwareio/simple-qrcode
because it does not have compatibility with baconqr 3.0

**Comment by eshimischi** [comment]
> simplesoftwareio/simple-qrcode

https://github.com/SimpleSoftwareIO/simple-qrcode/issues/304 as far as adapt a new version of baconqr, push them forward

**Pull request merged**
