### PR TITLE
Provide a way of customizing/disabling the default routes

### PR DESCRIPTION
**Pull request by MarkIvanowich**
A mirror of Jetstream's https://github.com/laravel/jetstream/pull/67

Enables a user to call Fortify::ignoreRoutes() in a provider's register method to disable the default routes and provide their own.
Also enables publishing of default routes into userland.

Relevant are https://github.com/laravel/fortify/issues/9, https://github.com/laravel/fortify/pull/10

### CODE REVIEW

**Comment by MarkIvanowich** [comment]
The Jetstream's version was merged while this one was closed? I figured since these two packages went hand-in-hand that they should be consistent in functionality.

I want to move my application login pages away from common endpoints that are typically brute forced. (`/login`, `/wp-login`, etc) Adding a prefix to the login route adds *just* enough additional security through obscurity.

**Comment by rodrigopedra** [comment]
Thanks @taylorotwell 

Much appreciated! =)

**Comment by anhofmann** [comment]
Why was the PR only partially merged? 
Publishing the routes did not make it into the master branch, or do I see it wrong?
If I want to adjust my routes, do I copy them manually from fortify into my routes, or what is the right way? I am relatively new to laravel and am trying to build customized login/register routes for different user roles in my app.

**Comment by driesvints** [comment]
@anhofmann you can just copy/paste them into your own routes.

**Comment by nicolailebek** [comment]
I copied "vendor/laravel/fortify/routes/routes.php" to "routes/fortify.php".

Then in "App/Providers/FortifyServiceProvider.php":

    public function boot() {
            $this->configureRoutes();
            ...
    }

    /**
     * Configure the routes offered by the application.
     *
     * @return void
     */
    protected function configureRoutes()
    {
        if (Fortify::$registersRoutes) {
            Route::group([
                'namespace' => 'Laravel\Fortify\Http\Controllers',
                'domain' => config('fortify.domain', null),
                'prefix' => config('fortify.path'),
            ], function () {
                $this->loadRoutesFrom(base_path('routes/fortify.php'));
            });
        }
    }

**Pull request merged**
