### PR TITLE
[1.x] Custom login and two factor login rules.

### PR DESCRIPTION
**Pull request by bangbangda**
Custom rules, may be more convenient to add validation rules.
eg authentication code validation.

### CODE REVIEW

**Comment by joelbutcher** [comment]
This would be better done via binding an implementation to a contract, then setting it via the Fortify class and calling it within the published service provider. Similar to the way fortify registers views fir its routes.

**Comment by driesvints** [comment]
Since we're not providing defaults in the implementing classes themselves this will be a breaking change for anyone already implementing Fortify.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by kukudeliu** [comment]
update: set login of custom verification rules.
reason: usually,verify the verification code.It will be more flexible.
@taylorotwell

**Comment by kukudeliu** [comment]
> Since we're not providing defaults in the implementing classes themselves this will be a breaking change for anyone already implementing Fortify.

It will not affect already implementing

**Comment by driesvints** [comment]
@kukudeliu it most definitely will for the people who have published the config file.

**Comment by joelbutcher** [comment]
@bangbangda @taylorotwell I've submitted a new PR for this which should avoid the breaking change and allow developers to specify the rules used for validating login & two-factor authentication requests. #199

**Comment by bangbangda** [comment]
Good idea, custom rules are necessary.
@joelbutcher

**Pull request closed without merging**
