### PR TITLE
Add redirect config after login, logout and registration

### PR DESCRIPTION
**Pull request by trbsi**
In this PR I added posibility to set redirection route after logout, login and registration. Registration route can be set inside config/fortify.php

### CODE REVIEW

**Comment by driesvints** [comment]
This is a breaking change because the current config relies on `fortify.home`. You're changing this back to the default which some people might have adjusted.

**Comment by trbsi** [comment]
That's true, if people get this change they will have to rely on this part

```
    'redirect' => [
        'login' => RouteServiceProvider::HOME,
        'registration' => RouteServiceProvider::HOME,
        'logout' => '/login',
    ],
```

What would be your suggestion here?
I think LogoutResponse.php can be adjusted and set default redirection to "/"?

**Comment by taylorotwell** [comment]
I dunno - maybe it is safer to just tell users to do this:

image

**Comment by trbsi** [comment]
So basically this: https://github.com/laravel/docs/pull/7063 ?

**Pull request closed without merging**
