### PR TITLE
[1.x] Prevent duplicate query using user from request

### LINKED ISSUE #120: AttemptToAuthenticate is not throwing validation exceptions by default
- Fortify Version: 1.6.1
- Laravel Version: 8.9.0
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 5.7.31

### Description:

This is the first time I'm using Fortify. I was trying to customize the login flow, because I want to change the default error bag on the `ValidationException`. But I noticed that the `throwFailedAuthenticationException` method on the `AttemptToAuthenticate` action is not being called, because the `RedirectIfTwoFactorAuthenticatable` action is calling `validateCredentials`, despite that I'm not using 2FA.

So the login pipeline is stopping at `RedirectIfTwoFactorAuthenticatable::validateCredentials()`, and the `AttemptToAuthenticate`, does not do anything, even though it's supposed to attempt to login or throw a validation exception.

### Steps To Reproduce:
1. Override `AttemptToAuthenticate`:
```php
use Illuminate\Validation\ValidationException;
use Laravel\Fortify\Actions\AttemptToAuthenticate;

class CustomAttemptToAuthenticate extends AttemptToAuthenticate 
{
    protected function throwFailedAuthenticationException($request)
    {
        try {
            parent::throwFailedAuthenticationException($request);
        } catch (ValidationException $e) {
            throw $e->errorBag('login');
        }
    }
}
```
2. Override login pipeline:
```php

Fortify::loginThrough(function () {
    return [
        config('fortify.limiters.login') ? null : EnsureLoginIsNotThrottled::class,
        RedirectIfTwoFactorAuthenticatable::class,
        CustomAttemptToAuthenticate::class,
        PrepareAuthenticatedSession::class,
    ];
});
```

3. Test the custom error bag:
```php
$response = $this->post('login', [
    'email' => 'invalid@email.com',
    'password' => 'password',
]);

 // this assertion fails
$response->assertSessionHasErrors('email', null, 'login');
```

4. Note the exception stack trace:
```php
$this->withoutExceptionHandling();

1   vendor/laravel/fortify/src/Actions/RedirectIfTwoFactorAuthenticatable.php:98
    Illuminate\Validation\ValidationException::withMessages()

2   vendor/laravel/fortify/src/Actions/RedirectIfTwoFactorAuthenticatable.php:80
    Laravel\Fortify\Actions\RedirectIfTwoFactorAuthenticatable::throwFailedAuthenticationException()

3   vendor/laravel/framework/src/Illuminate/Support/helpers.php:263
    Laravel\Fortify\Actions\RedirectIfTwoFactorAuthenticatable::Laravel\Fortify\Actions\{closure}()

4   vendor/laravel/fortify/src/Actions/RedirectIfTwoFactorAuthenticatable.php:82
    tap()

5   vendor/laravel/fortify/src/Actions/RedirectIfTwoFactorAuthenticatable.php:50
    Laravel\Fortify\Actions\RedirectIfTwoFactorAuthenticatable::validateCredentials()

6   vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
    Laravel\Fortify\Actions\RedirectIfTwoFactorAuthenticatable::handle()

7   vendor/laravel/fortify/src/Actions/EnsureLoginIsNotThrottled.php:39
    Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}()

8   vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
    Laravel\Fortify\Actions\EnsureLoginIsNotThrottled::handle()

9   vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
    Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}()

10  vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:60
    Illuminate\Pipeline\Pipeline::then()


```

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Resolve #120

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm still trying to understand why the middleware in charge of redirects would log someone in... 😅

**Comment by ricardogobbosouza** [comment]
I don't know if it's the best place to put it...I couldn't think of a better place 😅
But this prevents two database queries from being done when the user doesn't have enabled `two_factor_secret`

**Comment by driesvints** [comment]
@ricardogobbosouza walk me through this again: why does the `$request->user()` check you added not solve this? Why is the extra login action needed?

**Comment by taylorotwell** [comment]
Is there a big reason we care about two database queries with a very good index?

**Comment by ricardogobbosouza** [comment]
Search the user, but do not login https://github.com/laravel/fortify/blob/1.x/src/Actions/RedirectIfTwoFactorAuthenticatable.php#L50

If the user does not have `two_factor_secret`, he is not yet logged in and therefore is not included in the `$request->user()` request.

That's why the login was added so that in the next request it will not be necessary to make another query, whenever possible we should avoid duplicate queries.

**Comment by ricardogobbosouza** [comment]
Maybe we can pass the user in the request with another name and login in the correct middleware `AttemptAuthenticate` and not the middleware in charge of redirects

**Comment by ricardogobbosouza** [comment]
We can do this to leave the login responsibility with `AttemptToAuthenticate`

```php
// src/Actions/RedirectIfTwoFactorAuthenticatable.php

public function handle($request, $next)
{
    $user = $this->validateCredentials($request);

    if (optional($user)->two_factor_secret &&
        in_array(TwoFactorAuthenticatable::class, class_uses_recursive($user))) {
        return $this->twoFactorChallengeResponse($request, $user);
    }

    return $next($request->merge(['userWithoutTwoFactorSecret' => $user]));
}

// fortify/src/Actions/AttemptToAuthenticate.php 

public function handle($request, $next)
{
    if (Fortify::$authenticateUsingCallback) {
        return $this->handleUsingCustomCallback($request, $next);
    }

    if ($request->userWithoutTwoFactorSecret) {
        $this->guard->login($request->userWithoutTwoFactorSecret);
        
        return $next($request);
    }

    if ($this->guard->attempt(
        $request->only(Fortify::username(), 'password'),
        $request->filled('remember'))
    ) {
        return $next($request);
    }

    $this->throwFailedAuthenticationException($request);
}
```

**Comment by taylorotwell** [comment]
I just don't see a huge need to change the redirect middleware for a simple query on login. It is not going to be a performance bottleneck.

**Pull request closed without merging**
