### PR TITLE
[1.x] Added guard routes file

### PR DESCRIPTION
**Pull request by thecaliskan**
Hi;

I use this system with Nova. Two guards are required in this scenario. If there is a possibility of define, it should be. No time should be wasted to find.

Needs to be standard in config files on Laravel Official Projects.

Thanks

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why are two guards required? Can you elaborate?

**Comment by thecaliskan** [comment]
Hi;

Admin(web) guard used in Nova. Client guard used in Jetstream.

**Comment by taylorotwell** [comment]
Let the Jetstream guard be your default guard.

**Comment by thecaliskan** [comment]
Guard system is not third party library. Why don't you want to support ?

**Pull request closed without merging**
