### PR TITLE
Use the illuminate password rule

### PR DESCRIPTION
**Pull request by ricklambrechts**
I think it would be nice if we use the Password rule that is available so we do not have seperate classes with different functionalities.

The [`Illuminate\Validation\Rules\Password`](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Validation/Rules/Password.php) has more functionality than the Fortify implementation. For example this rule has mixed case and compromised check available.

### CODE REVIEW

**Comment by driesvints** [comment]
Although I'm not opposed, this is a breaking change for a minor release. You can't simply delete a class from a minor release.

**Comment by driesvints** [comment]
Try the master branch maybe?

**Comment by driesvints** [comment]
Or maybe better: re-send this without deleting the class and simply add a `@deprecated` annotation to it on top.

**Comment by ricklambrechts** [comment]
Thanks dries!

**Pull request closed without merging**
