### PR TITLE
Fixes Login throttle ternary condition inside `AuthenticatedSessionController`

### LINKED ISSUE #543: Login throttle ternary condition inside `AuthenticatedSessionController` seems incorrect
### Fortify Version

1.21.3

### Laravel Version

10.48.12

### PHP Version

8.2

### Database Driver & Version

MySQL 8.0 Docker container mysql/mysql-server:8.0

### Description

It seems that the ternary condition inside of `AuthenticatedSessionController` is inverted for `EnsureLoginIsNotThrottled` verification.

Location:
https://github.com/laravel/fortify/blob/a725684d17959c4750f3b441ff2e94ecde7793a1/src/Http/Controllers/AuthenticatedSessionController.php#L85-L91

It should like below:
```php
        return (new Pipeline(app()))->send($request)->through(array_filter([
            config('fortify.limiters.login') ? EnsureLoginIsNotThrottled::class : null,
            config('fortify.lowercase_usernames') ? CanonicalizeUsername::class : null,
            Features::enabled(Features::twoFactorAuthentication()) ? RedirectIfTwoFactorAuthenticatable::class : null,
            AttemptToAuthenticate::class,
            PrepareAuthenticatedSession::class,
        ]));
```

### Fortify own lockout handler is needed for different scenarios

- https://github.com/laravel/fortify/issues/336 
- https://github.com/laravel/fortify/issues/312

### Ideal scenario / my proposal
Have both protections by having different throttle configs for the Laravel middleware and Fortify own handler. We can have a smaller throttle rate for Fortify's own handler and a greater one for the middleware just in case of brute force. 

### Steps To Reproduce

1. Make sure to have the limiters defined in `config/fortify.php` as follows:
```
'limiters' => [
        'login' => 5,
        'two-factor' => 5,
    ],
```
2. Remove the throttle middleware from the `Route::post(RoutePath::for('login', '/login')` keeping everything else as is, see below: (Fortify has its own throttle error handlers, it shouldn't need to rely on Laravel defaults throttle middleware)
```
Route::post(RoutePath::for('login', '/login'), [AuthenticatedSessionController::class, 'store'])
        ->middleware(array_filter([
            'guest:'.config('fortify.guard')
        ]));
```
4. Now attempt multiple logins passing the limiter mark, you can try even 20 times. You'll never see the error "Too many login attempts. Please try again in X seconds.".
5. Now go to the default `AuthenticatedSessionController` in Fortify changing the line for the `EnsureLoginIsNotThrottled` below to `config('fortify.limiters.login') ? EnsureLoginIsNotThrottled::class : null`. Just invert it.
https://github.com/laravel/fortify/blob/a725684d17959c4750f3b441ff2e94ecde7793a1/src/Http/Controllers/AuthenticatedSessionController.php#L85-L87 
6. Now try to log in multiple times, at some point, you'll see the error "Too many requests. Please try again in X seconds.".

### PR DESCRIPTION
**Pull request by crynobone**
fixes #543

### CODE REVIEW

**Comment by taylorotwell** [comment]
The code is correct. 

If the limiter config is set we don't use Fortify's built-in Limiter `EnsureLoginIsNotThrottled` - we instead use the limiter the user defines which is assigned to the route in Fortify's route file.

**Comment by brnquester** [comment]
> The code is correct.
> 
> If the limiter config is set we don't use Fortify's built-in Limiter `EnsureLoginIsNotThrottled` - we instead use the limiter the user defines which is assigned to the route in Fortify's route file.

@taylorotwell - I'm sorry but I disagree. To begin all the confusion, the limiter that is set in the config is the same one used in the route in Fortify's route file. That alone is something I proposed in my PR #544 which was closed, to have two separate config parameters. Second, unless that limiter is totally empty or `false`(bool), it will never get to that throttle handler. 

See what I did in my PR, that would solve any confusion or conflicts and provide full granular control of what I want in the middleware and what I want in Fortify's throttle handler.

So the problem is, if I remove the limiter value as you are proposing, I still have a throttle in Fortify without any control over it. That is at minimum misleading IMO.

I kindly ask you to check what I did in my PR #544. I'll have it up again with the tests passing tonight.

**Comment by brnquester** [comment]
@taylorotwell  - new PR opened solving all this conflicts and confusions: https://github.com/laravel/fortify/pull/547

**Comment by brnquester** [comment]
@crynobone - Fix and improvement to that issue I reported: https://github.com/laravel/fortify/pull/547

**Pull request closed without merging**
