### PR TITLE
[2.x] Use code instead of email for the key

### PR DESCRIPTION
**Pull request by mokhosh**
This should resolve https://github.com/laravel/fortify/issues/236

Also I was surprised to see that all the tests passed before and after the change. I would love to add tests for this as well, but I'm not sure how to test a two step verification challenge.
It shouldn't be an issue though, since there were no tests in the first place.

### CODE REVIEW

**Comment by driesvints** [comment]
@taylorotwell I checked Jetstream and I think this change can maybe still be made in 1.x as it's never directly used in Jetstream. Instead, errors are looped over here: https://github.com/laravel/jetstream/blob/2.x/resources/views/components/validation-errors.blade.php

So maybe we should target 1.x?

**Comment by mokhosh** [comment]
@driesvints I guess it's ok for Jetstream, but this can be breaking for those who use Fortify and have customised 2FA flow.

I'm using `email` key in one of my websites just because it's the only way to know if there's a 2FA error now.

**Comment by driesvints** [comment]
@mokhosh that's true.

**Comment by taylorotwell** [comment]
Could be a breaking change.

**Pull request merged**
