### PR TITLE
Feature/stateless email verification

### PR DESCRIPTION
**Pull request by rcerljenko**
Re-targeted for master branch.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by rcerljenko** [comment]
@taylorotwell @driesvints could I ask why was it declined? We covered the topic here => https://github.com/laravel/fortify/issues/308.
I know that tests are failing but besides that was anything else wrong?

**Comment by driesvints** [comment]
@rcerljenko I've pinged Taylor about this

**Comment by rcerljenko** [comment]
@driesvints thanks!

Also, a little explanation about why we need an extra config for verification model.

We could avoid this by putting the User model directly as a param of the controller so that is route model binded but I wanted to be configurable since somebody could have different auth model for this.
Everything else should be straightforward...

Ping me if you need any aditional info.

**Comment by driesvints** [comment]
@rcerljenko we've backlogged in our internal Trello. So for right now we're not taking any action on this, sorry.

**Comment by rcerljenko** [comment]
@driesvints ok... thanks for the update

**Comment by Danoctum** [comment]
Will this ever be accepted?

Fortify is not a true headless authentication library, because it is very much reliant on a specific way of implementing a front-end to verify an email address. If I'd like to use Sanctum for a mobile app, and Fortify for authentication, I'd always need a website where a user can login in order for the email to be verified.

**Pull request closed without merging**
